/* Navora 3D - SPA localStorage */
const APP_KEY='navora3d_db_v1';
const LOGIN={user:'administrador',pass:'Couve5flor*'};
const MODULE_LABELS={dashboard:'Dashboard',cadastros:'Cadastros',catalogo:'Catálogo de Produtos',estoque:'Estoque',compras:'Compras',producao:'Produção',vendas:'Vendas',financeiro:'Financeiro',configuracoes:'Configurações'};
const nowISO=()=>new Date().toISOString();
const uid=(p='ID')=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
const dateBR=v=>v?new Date(v).toLocaleDateString('pt-BR'):'-';
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const num=v=>Number(String(v??'').replace(',','.'))||0;
const blankDB=()=>({meta:{createdAt:nowISO(),updatedAt:nowISO()},cadastros:{clientes:[],fornecedores:[],materiais:[],categorias:[],cores:[]},produtos:[],compras:[],estoque:[],producoes:[],vendas:[],financeiro:[]});
let db=loadDB(); let currentModule='dashboard'; let dashboardCharts={}; let cadTab='clientes';
function loadDB(){try{return {...blankDB(),...JSON.parse(localStorage.getItem(APP_KEY)||'{}')}}catch{return blankDB()}}
function saveDB(){db.meta.updatedAt=nowISO();localStorage.setItem(APP_KEY,JSON.stringify(db));}
function toast(msg,type='success'){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=msg;document.getElementById('toast-container').appendChild(el);setTimeout(()=>el.remove(),2800)}
function setModule(m){currentModule=m;document.querySelectorAll('.nav-item[data-module]').forEach(b=>b.classList.toggle('active',b.dataset.module===m));document.getElementById('page-title').textContent=MODULE_LABELS[m];document.getElementById('page-kicker').textContent=m==='dashboard'?'Visão geral':'Gestão operacional';renderModule();window.scrollTo({top:0,behavior:'smooth'})}
function renderModule(){const root=document.getElementById('module-root');root.innerHTML=''; if(currentModule==='dashboard')renderDashboard(root); if(currentModule==='cadastros')renderCadastros(root); if(currentModule==='catalogo')renderCatalogo(root); if(currentModule==='estoque')renderEstoque(root); if(currentModule==='compras')renderCompras(root); if(currentModule==='producao')renderProducao(root); if(currentModule==='vendas')renderVendas(root); if(currentModule==='financeiro')renderFinanceiro(root); if(currentModule==='configuracoes')renderConfiguracoes(root)}

function renderDashboard(root){
 const sales=db.vendas; const revenue=sales.reduce((s,x)=>s+num(x.valorFinal),0); const profit= sales.reduce((s,x)=>s+(num(x.valorFinal)-estimatedCost(x.produtoId,x.qtde)),0);
 root.innerHTML=`<div class="section-head"><div><h2>Painel gerencial</h2><p>Indicadores e evolução das vendas da Navora 3D.</p></div><div class="toolbar"><button class="btn btn-secondary" id="dash-reset">Limpar filtros</button></div></div>
 <div class="filters"><label>Período início<input type="date" id="df-from"></label><label>Período fim<input type="date" id="df-to"></label><label>Cliente<select id="df-client"><option value="">Todos</option>${db.cadastros.clientes.map(c=>`<option value="${c.id}">${esc(c.nome)}</option>`).join('')}</select></label><label>Produto<select id="df-product"><option value="">Todos</option>${db.produtos.map(p=>`<option value="${p.id}">${esc(p.descricao)}</option>`).join('')}</select></label><label>Categoria<select id="df-category"><option value="">Todas</option>${db.cadastros.categorias.map(c=>`<option value="${c.id}">${esc(c.descricao)}</option>`).join('')}</select></label></div>
 <div class="cards"><div class="card metric"><div class="label">Faturamento total</div><div class="value" id="dash-revenue">${money(revenue)}</div><div class="sub">Vendas no período selecionado</div></div><div class="card metric"><div class="label">Lucro estimado</div><div class="value" id="dash-profit">${money(profit)}</div><div class="sub">Receita menos custo estimado</div></div><div class="card metric"><div class="label">Vendas realizadas</div><div class="value" id="dash-count">${sales.length}</div><div class="sub">Pedidos registrados</div></div></div>
 <div class="grid-2"><div class="card chart-card"><h3>Vendas dos últimos 30 dias</h3><div class="chart-wrap"><canvas id="sales-chart"></canvas></div></div><div class="card chart-card"><h3>Resumo por produto</h3><div class="chart-wrap"><canvas id="product-chart"></canvas></div></div></div>`;
 ['df-from','df-to','df-client','df-product','df-category'].forEach(id=>document.getElementById(id).addEventListener('change',updateDashboard));document.getElementById('dash-reset').onclick=()=>{['df-from','df-to','df-client','df-product','df-category'].forEach(id=>document.getElementById(id).value='');updateDashboard()};
 updateDashboard();
}
function filteredSales(){const from=document.getElementById('df-from')?.value,to=document.getElementById('df-to')?.value,cl=document.getElementById('df-client')?.value,pr=document.getElementById('df-product')?.value,cat=document.getElementById('df-category')?.value;return db.vendas.filter(s=>{const d=s.data?.slice(0,10);const p=db.produtos.find(x=>x.id===s.produtoId);return (!from||d>=from)&&(!to||d<=to)&&(!cl||s.clienteId===cl)&&(!pr||s.produtoId===pr)&&(!cat||p?.categoriaId===cat)})}
function updateDashboard(){const sales=filteredSales();const revenue=sales.reduce((s,x)=>s+num(x.valorFinal),0);const profit=sales.reduce((s,x)=>s+(num(x.valorFinal)-estimatedCost(x.produtoId,x.qtde)),0);document.getElementById('dash-revenue').textContent=money(revenue);document.getElementById('dash-profit').textContent=money(profit);document.getElementById('dash-count').textContent=sales.length;renderCharts(sales)}
function estimatedCost(productId,qty){const p=db.produtos.find(x=>x.id===productId);if(!p)return 0;const comps=db.compras.filter(c=>c.produtoId===productId);if(comps.length)return comps.reduce((s,c)=>s+((num(c.valorTotal)/Math.max(1,num(c.qtde))) * num(qty)),0);return 0}
function renderCharts(sales){
 const labels=[]; const vals=[];
 for(let i=29;i>=0;i--){
  const d=new Date(); d.setDate(d.getDate()-i);
  const key=d.toISOString().slice(0,10);
  labels.push(d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}));
  vals.push(sales.filter(s=>(s.data||'').slice(0,10)===key).reduce((a,x)=>a+num(x.valorFinal),0));
 }
 if(dashboardCharts.sales) dashboardCharts.sales.destroy();
 if(dashboardCharts.products) dashboardCharts.products.destroy();
 dashboardCharts.sales=new Chart(document.getElementById('sales-chart'),{
  type:'line',
  data:{labels,datasets:[{label:'Faturamento',data:vals,tension:.35,fill:true}]},
  options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}}
 });
 const map={};
 sales.forEach(s=>map[s.produtoId]=(map[s.produtoId]||0)+num(s.valorFinal));
 const pNames=Object.keys(map).map(id=>db.produtos.find(p=>p.id===id)?.descricao||'Produto');
 dashboardCharts.products=new Chart(document.getElementById('product-chart'),{
  type:'doughnut',
  data:{labels:pNames.length?pNames:['Sem vendas'],datasets:[{data:pNames.length?Object.values(map):[1]}]},
  options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}}}
 });
}


const cadDefs={clientes:{title:'Clientes',fields:[['nome','Nome completo','text',true],['cpf','CPF/CNPJ','text',false],['telefone','Telefone','text',false],['email','E-mail','email',false],['cidade','Cidade','text',false],['observacoes','Observações','textarea',false]]},fornecedores:{title:'Fornecedores',fields:[['nome','Nome/Razão Social','text',true],['cpf','CPF/CNPJ','text',false],['contato','Contato','text',false],['email','E-mail','email',false],['cidade','Cidade','text',false],['observacoes','Observações','textarea',false]]},materiais:{title:'Materiais',fields:[['descricao','Material','text',true],['observacoes','Observações','textarea',false]]},categorias:{title:'Categorias',fields:[['descricao','Categoria','text',true]]},cores:{title:'Cores',fields:[['descricao','Cor','text',true]]}};
function renderCadastros(root){const def=cadDefs[cadTab];root.innerHTML=`<div class="section-head"><div><h2>Cadastros centralizados</h2><p>Cadastre, consulte, altere e remova os dados mestres da operação.</p></div><button class="btn btn-primary" id="add-cadastro">+ Novo cadastro</button></div><div class="tabs">${Object.entries(cadDefs).map(([k,v])=>`<button class="tab ${k===cadTab?'active':''}" data-tab="${k}">${v.title}</button>`).join('')}</div><div class="card panel"><div class="table-wrap" id="cad-table"></div></div>`;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{cadTab=b.dataset.tab;renderCadastros(root)});document.getElementById('add-cadastro').onclick=()=>openCadModal(cadTab);renderCadTable()}
function renderCadTable(){const def=cadDefs[cadTab],rows=db.cadastros[cadTab]||[];const head=def.fields.map(f=>`<th>${f[1]}</th>`).join('');document.getElementById('cad-table').innerHTML=rows.length?`<table class="data-table"><thead><tr>${head}<th>Ações</th></tr></thead><tbody>${rows.map(r=>`<tr>${def.fields.map(f=>`<td>${esc(r[f[0]])||'-'}</td>`).join('')}<td><div class="actions"><button class="small-btn" onclick="openCadModal('${cadTab}','${r.id}')">Editar</button><button class="small-btn" onclick="deleteCad('${cadTab}','${r.id}')">Excluir</button></div></td></tr>`).join('')}</tbody></table>`:`<div class="empty-state"><strong>Nenhum registro</strong>Comece adicionando um novo ${def.title.toLowerCase().slice(0,-1)}.</div>`}
function openCadModal(type,id){const def=cadDefs[type],r=(db.cadastros[type]||[]).find(x=>x.id===id)||{};openModal(def.title,id?'Editar cadastro':'Novo cadastro',`<div class="form-grid">${def.fields.map(f=>{const [key,label,typ,required]=f;return `<label class="${typ==='textarea'?'col-12':'col-6'}">${label}${required?' *':''}${typ==='textarea'?`<textarea id="f_${key}">${esc(r[key])}</textarea>`:`<input id="f_${key}" type="${typ}" value="${esc(r[key]||'')}" ${required?'required':''}>`}</label>`}).join('')}</div>`,()=>{const obj={id:r.id||uid(type.slice(0,3).toUpperCase())};for(const [key,label,typ,required] of def.fields){const v=document.getElementById('f_'+key).value.trim();if(required&&!v){toast(`Preencha ${label}.`,'error');return}obj[key]=v}if(id)Object.assign(r,obj);else db.cadastros[type].push(obj);saveDB();closeModal();renderCadastros(document.getElementById('module-root'));toast('Cadastro salvo.');});}
window.openCadModal=openCadModal;window.deleteCad=(type,id)=>{if(!confirm('Excluir este cadastro?'))return;db.cadastros[type]=db.cadastros[type].filter(x=>x.id!==id);saveDB();renderCadastros(document.getElementById('module-root'));toast('Cadastro excluído.','error')};

function renderCatalogo(root){root.innerHTML=`<div class="section-head"><div><h2>Catálogo de Produtos</h2><p>Produtos vendidos, parâmetros de produção e últimas vendas.</p></div><button class="btn btn-primary" id="add-prod">+ Novo produto</button></div><div class="card panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Descrição</th><th>Categoria</th><th>Material</th><th>Cor</th><th>Dimensões</th><th>Tempo</th><th>Preço sugerido</th><th>Ações</th></tr></thead><tbody>${db.produtos.length?db.produtos.map(p=>{const c=db.cadastros.categorias.find(x=>x.id===p.categoriaId)?.descricao||'-',m=db.cadastros.materiais.find(x=>x.id===p.materialId)?.descricao||'-',co=db.cadastros.cores.find(x=>x.id===p.corId)?.descricao||'-';return `<tr><td><strong>${esc(p.descricao)}</strong></td><td>${esc(c)}</td><td>${esc(m)}</td><td>${esc(co)}</td><td>${esc(p.dimensoes)}</td><td>${p.horas||0}h ${p.minutos||0}m</td><td>${money(p.preco)}</td><td><div class="actions"><button class="small-btn" onclick="openProductModal('${p.id}')">Editar</button><button class="small-btn" onclick="showLastSales('${p.id}')">Últimas vendas</button><button class="small-btn" onclick="deleteProduct('${p.id}')">Excluir</button></div></td></tr>`}).join(''):`<tr><td colspan="8"><div class="empty-state">Nenhum produto cadastrado.</div></td></tr>`}</tbody></table></div></div>`;document.getElementById('add-prod').onclick=()=>openProductModal()}
function productForm(r={}){return `<div class="form-grid"><label class="col-6">Descrição *<input id="p_desc" value="${esc(r.descricao||'')}" required></label><label class="col-6">Categoria *<select id="p_cat" required><option value="">Selecione</option>${db.cadastros.categorias.map(x=>`<option value="${x.id}" ${r.categoriaId===x.id?'selected':''}>${esc(x.descricao)}</option>`).join('')}</select></label><label class="col-6">Material *<select id="p_mat" required><option value="">Selecione</option>${db.cadastros.materiais.map(x=>`<option value="${x.id}" ${r.materialId===x.id?'selected':''}>${esc(x.descricao)}</option>`).join('')}</select></label><label class="col-6">Cor *<select id="p_cor" required><option value="">Selecione</option>${db.cadastros.cores.map(x=>`<option value="${x.id}" ${r.corId===x.id?'selected':''}>${esc(x.descricao)}</option>`).join('')}</select></label><label class="col-6">Dimensões *<input id="p_dim" placeholder="20,00 x 10,50 x 5,00" value="${esc(r.dimensoes||'')}" required></label><label class="col-3">Horas *<input id="p_h" type="number" min="0" value="${r.horas||0}" required></label><label class="col-3">Minutos *<input id="p_m" type="number" min="0" max="59" value="${r.minutos||0}" required></label><label class="col-6">Preço sugerido (R$) *<input id="p_price" inputmode="decimal" value="${String(r.preco??'').replace('.',',')}" required></label><div class="col-12 inline-note">Dimensões são armazenadas como texto para permitir formatos como “20,00 x 10,00 x 5,00”.</div></div>`}
window.openProductModal=(id)=>{const r=db.produtos.find(x=>x.id===id)||{};openModal('Catálogo de Produtos',id?'Editar produto':'Novo produto',productForm(r),()=>{const required=['p_desc','p_cat','p_mat','p_cor','p_dim','p_h','p_m','p_price'];if(required.some(x=>!document.getElementById(x).value.trim())){toast('Preencha os campos obrigatórios.','error');return}const obj={id:r.id||uid('PROD'),descricao:document.getElementById('p_desc').value.trim(),categoriaId:document.getElementById('p_cat').value,materialId:document.getElementById('p_mat').value,corId:document.getElementById('p_cor').value,dimensoes:document.getElementById('p_dim').value.trim(),horas:num(document.getElementById('p_h').value),minutos:Math.floor(num(document.getElementById('p_m').value)),qtde:num(r.qtde)||0,preco:num(document.getElementById('p_price').value)};if(id)Object.assign(r,obj);else db.produtos.push(obj);saveDB();closeModal();renderCatalogo(document.getElementById('module-root'));toast('Produto salvo.')})};window.deleteProduct=id=>{if(!confirm('Excluir produto?'))return;db.produtos=db.produtos.filter(x=>x.id!==id);saveDB();renderCatalogo(document.getElementById('module-root'));toast('Produto excluído.','error')};
function showLastSales(id){const p=db.produtos.find(x=>x.id===id),sales=db.vendas.filter(s=>s.produtoId===id).sort((a,b)=>new Date(b.data)-new Date(a.data)).slice(0,3);openModal('Últimas vendas',p?.descricao||'Produto',sales.length?`<table class="data-table"><thead><tr><th>Data</th><th>Cliente</th><th>Dimensões</th><th>Valor</th><th>Observações</th></tr></thead><tbody>${sales.map(s=>`<tr><td>${dateBR(s.data)}</td><td>${esc(db.cadastros.clientes.find(c=>c.id===s.clienteId)?.nome||'-')}</td><td>${esc(p?.dimensoes||'-')}</td><td>${money(s.valorFinal)}</td><td>${esc(s.observacoes||'-')}</td></tr>`).join('')}</tbody></table>`:`<div class="empty-state"><strong>Sem vendas</strong>Ainda não existem vendas para este produto.</div>`,null)}

function renderEstoque(root){const q={prod:'',forn:'',cor:'',tipo:'',mat:''};root.innerHTML=`<div class="section-head"><div><h2>Estoque</h2><p>Consulte apenas o produto/material necessário e faça ajustes de estoque.</p></div></div><div class="filters"><label>Produto<input id="s_prod" placeholder="Pesquisar"></label><label>Fornecedor<select id="s_forn"><option value="">Todos</option>${db.cadastros.fornecedores.map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('')}</select></label><label>Cor<select id="s_cor"><option value="">Todas</option>${db.cadastros.cores.map(x=>`<option value="${x.id}">${esc(x.descricao)}</option>`).join('')}</select></label><label>Tipo<select id="s_tipo"><option value="">Todos</option><option>Filamento</option><option>Componente</option><option>Outro</option></select></label><label>Material<select id="s_mat"><option value="">Todos</option>${db.cadastros.materiais.map(x=>`<option value="${x.id}">${esc(x.descricao)}</option>`).join('')}</select></label></div><div class="card panel"><div id="stock-result"></div></div>`;['s_prod','s_forn','s_cor','s_tipo','s_mat'].forEach(id=>document.getElementById(id).addEventListener('input',renderStockTable));renderStockTable()}
function renderStockTable(){const prod=document.getElementById('s_prod').value.toLowerCase(),forn=document.getElementById('s_forn').value,cor=document.getElementById('s_cor').value,tipo=document.getElementById('s_tipo').value,mat=document.getElementById('s_mat').value;const rows=db.estoque.filter(x=>(!prod||x.descricao.toLowerCase().includes(prod))&&(!forn||x.fornecedorId===forn)&&(!cor||x.corId===cor)&&(!tipo||x.tipo===tipo)&&(!mat||x.materialId===mat));document.getElementById('stock-result').innerHTML=rows.length?`<table class="data-table"><thead><tr><th>Produto</th><th>Fornecedor</th><th>Cor</th><th>Tipo</th><th>Material</th><th>Qtde estoque</th><th>Situação</th><th>Ações</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.descricao)}</td><td>${esc(db.cadastros.fornecedores.find(f=>f.id===x.fornecedorId)?.nome||'-')}</td><td>${esc(db.cadastros.cores.find(c=>c.id===x.corId)?.descricao||x.cor||'-')}</td><td>${esc(x.tipo)}</td><td>${esc(db.cadastros.materiais.find(m=>m.id===x.materialId)?.descricao||x.material||'-')}</td><td><strong>${num(x.qtde).toFixed(2)}</strong></td><td><span class="status-pill ${num(x.qtde)>0?'status-ok':'status-empty'}">${num(x.qtde)>0?'Disponível':'Sem estoque'}</span></td><td><button class="small-btn" onclick="adjustStock('${x.id}')">Ajustar</button></td></tr>`).join('')}</tbody></table>`:`<div class="empty-state"><strong>Nenhum resultado</strong>Pesquise um produto ou material para visualizar o estoque.</div>`}
window.adjustStock=id=>{const x=db.estoque.find(e=>e.id===id);openModal('Ajuste de estoque',x?.descricao||'',`<div class="form-grid"><label class="col-6">Quantidade atual<input value="${num(x.qtde).toFixed(2)}" disabled></label><label class="col-6">Novo saldo<input id="stk_new" inputmode="decimal" value="${num(x.qtde).toFixed(2)}"></label><label class="col-12">Motivo<textarea id="stk_note" placeholder="Ex.: perda, correção, inventário..."></textarea></label></div>`,()=>{x.qtde=num(document.getElementById('stk_new').value);x.updatedAt=nowISO();saveDB();closeModal();renderEstoque(document.getElementById('module-root'));toast('Estoque ajustado.')})}

function renderCompras(root){root.innerHTML=`<div class="section-head"><div><h2>Compras</h2><p>Registre matérias-primas, componentes, embalagens e demais insumos.</p></div><button class="btn btn-primary" id="add-compra">+ Nova compra</button></div><div class="card panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Descrição</th><th>Tipo</th><th>Fornecedor</th><th>Qtde (g)</th><th>Cor</th><th>Alerta mín.</th><th>Valor</th><th>Frete</th><th>Outros</th><th>Total</th><th>Ações</th></tr></thead><tbody>${db.compras.length?db.compras.map(x=>`<tr><td>${esc(x.descricao)}</td><td>${esc(x.tipo)}</td><td>${esc(db.cadastros.fornecedores.find(f=>f.id===x.fornecedorId)?.nome||'-')}</td><td>${num(x.qtde).toFixed(2)}</td><td>${esc(db.cadastros.cores.find(c=>c.id===x.corId)?.descricao||'-')}</td><td>${num(x.alerta).toFixed(2)}</td><td>${money(x.valor)}</td><td>${money(x.frete)}</td><td>${money(x.outros)}</td><td><strong>${money(x.valorTotal)}</strong></td><td><div class="actions"><button class="small-btn" onclick="openCompraModal('${x.id}')">Editar</button><button class="small-btn" onclick="deleteCompra('${x.id}')">Excluir</button></div></td></tr>`).join(''):`<tr><td colspan="11"><div class="empty-state">Nenhuma compra cadastrada.</div></td></tr>`}</tbody></table></div></div>`;document.getElementById('add-compra').onclick=()=>openCompraModal()}
function compraForm(r={}){return `<div class="form-grid"><label class="col-6">Descrição *<input id="c_desc" value="${esc(r.descricao||'')}" required></label><label class="col-3">Tipo *<select id="c_tipo" required><option value="">Selecione</option>${['Filamento','Componente','Outros'].map(v=>`<option ${r.tipo===v?'selected':''}>${v}</option>`).join('')}</select></label><label class="col-3">Fornecedor *<select id="c_forn" required><option value="">Selecione</option>${db.cadastros.fornecedores.map(x=>`<option value="${x.id}" ${r.fornecedorId===x.id?'selected':''}>${esc(x.nome)}</option>`).join('')}</select></label><label class="col-4">Qtde (g) *<input id="c_q" inputmode="decimal" value="${r.qtde??''}" required></label><label class="col-4">Cor *<select id="c_cor" required><option value="">Selecione</option>${db.cadastros.cores.map(x=>`<option value="${x.id}" ${r.corId===x.id?'selected':''}>${esc(x.descricao)}</option>`).join('')}</select></label><label class="col-4">Material<select id="c_mat"><option value="">Selecione</option>${db.cadastros.materiais.map(x=>`<option value="${x.id}" ${r.materialId===x.id?'selected':''}>${esc(x.descricao)}</option>`).join('')}</select></label><label class="col-4">Alerta estoque mínimo<input id="c_alerta" inputmode="decimal" value="${r.alerta??''}"></label><label class="col-4">Valor (R$)<input id="c_valor" inputmode="decimal" value="${r.valor??''}"></label><label class="col-4">Frete (R$)<input id="c_frete" inputmode="decimal" value="${r.frete??''}"></label><label class="col-4">Outros (R$)<input id="c_outros" inputmode="decimal" value="${r.outros??''}"></label><div class="col-12 inline-note">Valor total calculado = valor da compra + frete + outros.</div></div>`}
window.openCompraModal=id=>{const r=db.compras.find(x=>x.id===id)||{};openModal('Compras',id?'Editar compra':'Nova compra',compraForm(r),()=>{if(!document.getElementById('c_desc').value.trim()||!document.getElementById('c_tipo').value||!document.getElementById('c_forn').value||!document.getElementById('c_q').value||!document.getElementById('c_cor').value){toast('Preencha os campos obrigatórios.','error');return}const obj={id:r.id||uid('COMP'),descricao:document.getElementById('c_desc').value.trim(),tipo:document.getElementById('c_tipo').value,fornecedorId:document.getElementById('c_forn').value,qtde:num(document.getElementById('c_q').value),corId:document.getElementById('c_cor').value,materialId:document.getElementById('c_mat').value,alerta:num(document.getElementById('c_alerta').value),valor:num(document.getElementById('c_valor').value),frete:num(document.getElementById('c_frete').value),outros:num(document.getElementById('c_outros').value)};obj.valorTotal=obj.valor+obj.frete+obj.outros;if(id)Object.assign(r,obj);else db.compras.push(obj);syncStockFromCompra(obj);saveDB();closeModal();renderCompras(document.getElementById('module-root'));toast('Compra salva e estoque atualizado.')})};
function syncStockFromCompra(c){let x=db.estoque.find(e=>e.descricao.toLowerCase()===c.descricao.toLowerCase()&&e.fornecedorId===c.fornecedorId&&e.tipo===c.tipo&&e.corId===c.corId&&e.materialId===c.materialId);if(!x){x={id:uid('EST'),descricao:c.descricao,tipo:c.tipo,fornecedorId:c.fornecedorId,corId:c.corId,materialId:c.materialId,qtde:0,alerta:c.alerta};db.estoque.push(x)}x.alerta=c.alerta;if(!c._stockApplied){x.qtde+=c.qtde;c._stockApplied=true}}
window.deleteCompra=id=>{if(!confirm('Excluir esta compra? Isso não reverte automaticamente o estoque já lançado.'))return;db.compras=db.compras.filter(x=>x.id!==id);saveDB();renderCompras(document.getElementById('module-root'));toast('Compra excluída.','error')};

function productionCode(o){return o?.codigo||'PRD'+String((db.producoes.indexOf(o)+1)||1).padStart(6,'0')}
function nextProductionCode(){const max=db.producoes.reduce((m,o)=>{const n=String(o.codigo||o.id||'').match(/^PRD(\d+)$/i);return n?Math.max(m,Number(n[1])):m},db.producoes.length);return `PRD${String(max+1).padStart(6,'0')}`}
function renderProducao(root){root.innerHTML=`<div class="section-head"><div><h2>Produção</h2><p>Ordens de produção, consumo de materiais e entrada de produtos acabados.</p></div><button class="btn btn-primary" id="add-op">+ Nova ordem</button></div><div class="card panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Código</th><th>Produto</th><th>Cor</th><th>Qtde</th><th>Material</th><th>Status</th><th>Observações</th><th>Ações</th></tr></thead><tbody>${db.producoes.length?db.producoes.map(o=>`<tr><td><strong>${esc(productionCode(o))}</strong></td><td>${esc(db.produtos.find(p=>p.id===o.produtoId)?.descricao||'-')}</td><td>${esc(db.cadastros.cores.find(c=>c.id===o.corId)?.descricao||'-')}</td><td>${num(o.qtde)}</td><td>${o.materiais.map(m=>esc(m.descricao)).join(', ')}</td><td>${productionStatus(o.status)}</td><td>${esc(o.observacoes||'-')}</td><td><div class="actions"><button class="small-btn" onclick="openOPModal('${o.id}')">Editar</button><button class="small-btn" onclick="generateSale('${o.id}')">Gerar venda</button><button class="small-btn" onclick="deleteOP('${o.id}')">Excluir</button></div></td></tr>`).join(''):`<tr><td colspan="8"><div class="empty-state">Nenhuma ordem de produção.</div></td></tr>`}</tbody></table></div></div>`;document.getElementById('add-op').onclick=()=>openOPModal()}
const productionStatus=s=>`<span class="status-pill ${s==='Finalizado'?'status-ok':s==='Em produção'?'status-production':'status-wait'}">${esc(s)}</span>`;
function availableProductionStocks(selected=[]){const selectedIds=new Set(selected.map(m=>m.estoqueId));return db.estoque.filter(s=>num(s.qtde)>0||selectedIds.has(s.id))}
function materialRowLabel(stock){const cor=db.cadastros.cores.find(c=>c.id===stock.corId)?.descricao||stock.cor||'-';return `${esc(stock.descricao)} • ${esc(stock.tipo||'Outro')} • estoque ${num(stock.qtde).toFixed(2)}${cor&&cor!=='-'?` • ${esc(cor)}`:''}`}
function selectedMaterialsTable(materials=[]){return materials.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Material</th><th>Cor</th><th>Gramas</th><th>Ação</th></tr></thead><tbody>${materials.map((m,i)=>`<tr><td>${esc(m.descricao)}</td><td>${esc(db.cadastros.cores.find(c=>c.id===m.corId)?.descricao||'-')}</td><td>${num(m.gramas).toFixed(2)}</td><td><button type="button" class="small-btn" data-remove-material="${i}">Remover</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="inline-note">Nenhum material adicionado à ordem.</div>`}
function opForm(r={}){const materials=(r.materiais||[]).map(m=>({...m}));const available=availableProductionStocks(materials);return `<div class="form-grid"><label class="col-6">Produto *<select id="o_prod" required><option value="">Selecione</option>${db.produtos.map(x=>`<option value="${x.id}" ${r.produtoId===x.id?'selected':''}>${esc(x.descricao)}</option>`).join('')}</select></label><label class="col-3">Cor *<select id="o_cor" required><option value="">Selecione</option>${db.cadastros.cores.map(x=>`<option value="${x.id}" ${r.corId===x.id?'selected':''}>${esc(x.descricao)}</option>`).join('')}</select></label><label class="col-3">Qtde *<input id="o_q" type="number" min="1" value="${r.qtde||1}" required></label><div class="col-12"><div class="section-head compact"><div><strong>Materiais utilizados</strong><p>As opções de cor/filamento ficam ocultas até você adicionar um material.</p></div><button type="button" class="btn btn-secondary" id="op-add-material">+ Adicionar material</button></div><div id="op-material-picker" class="production-material-picker hidden"><label class="col-6">Cor / Filamento<select id="op_material_select"><option value="">Selecione</option>${available.map(s=>`<option value="${s.id}">${materialRowLabel(s)}</option>`).join('')}</select></label><label class="col-3">Cor<input id="op_material_color" value="" readonly></label><label class="col-3">Gramas<input id="op_material_grams" inputmode="decimal" placeholder="0,00"></label><div class="col-12"><button type="button" class="btn btn-primary" id="op-confirm-material">Adicionar à ordem</button></div></div><div id="op-material-list">${selectedMaterialsTable(materials)}</div></div><label class="col-3">Status *<select id="o_status" required>${['Aguardando','Em produção','Finalizado'].map(v=>`<option ${r.status===v?'selected':''}>${v}</option>`).join('')}</select></label><label class="col-9">Observações<textarea id="o_obs">${esc(r.observacoes||'')}</textarea></label></div>`}
window.openOPModal=id=>{const r=db.producoes.find(x=>x.id===id)||{};openModal('Produção',id?'Editar ordem de produção':'Nova ordem de produção',opForm(r),()=>{const prod=document.getElementById('o_prod').value,cor=document.getElementById('o_cor').value,q=num(document.getElementById('o_q').value),status=document.getElementById('o_status').value;if(!prod||!cor||q<=0||!status){toast('Preencha os campos obrigatórios.','error');return}const materials=JSON.parse(document.getElementById('op_material_list_json').value||'[]');if(!materials.length){toast('Adicione ao menos um material.','error');return}if(materials.some(m=>m.gramas<=0)){toast('Informe as gramas para cada material selecionado.','error');return}if(materials.some(m=>{const stock=db.estoque.find(x=>x.id===m.estoqueId);return !stock||(!r.finishedApplied&&num(m.gramas)>num(stock.qtde))})){toast('A quantidade em gramas excede o estoque disponível.','error');return}const obj={id:r.id||uid('OP'),codigo:r.codigo||nextProductionCode(),produtoId:prod,corId:cor,qtde:q,materiais:materials,status,observacoes:document.getElementById('o_obs').value.trim(),finishedApplied:r.finishedApplied||false};if(id){Object.assign(r,obj);if(r.status==='Finalizado'&&!r.finishedApplied)applyFinishedProduction(r)}else{db.producoes.push(obj);if(obj.status==='Finalizado')applyFinishedProduction(obj)}saveDB();closeModal();renderProducao(document.getElementById('module-root'));toast('Ordem de produção salva.')})
setTimeout(()=>{let materialList=[...(r.materiais||[])].map(m=>({...m}));const hidden=document.createElement('input');hidden.type='hidden';hidden.id='op_material_list_json';hidden.value=JSON.stringify(materialList);document.querySelector('.modal-body').appendChild(hidden);const picker=document.getElementById('op-material-picker'),select=document.getElementById('op_material_select'),color=document.getElementById('op_material_color'),grams=document.getElementById('op_material_grams'),list=document.getElementById('op-material-list');const sync=()=>{hidden.value=JSON.stringify(materialList);list.innerHTML=selectedMaterialsTable(materialList);list.querySelectorAll('[data-remove-material]').forEach(btn=>btn.onclick=()=>{materialList.splice(Number(btn.dataset.removeMaterial),1);sync()})};const updateColor=()=>{const stock=db.estoque.find(x=>x.id===select.value);color.value=stock?(db.cadastros.cores.find(c=>c.id===stock.corId)?.descricao||stock.cor||''):'';};document.getElementById('op-add-material').onclick=()=>{picker.classList.toggle('hidden');if(!picker.classList.contains('hidden'))select.focus()};select.addEventListener('change',updateColor);document.getElementById('op-confirm-material').onclick=()=>{const stock=db.estoque.find(x=>x.id===select.value);const g=num(grams.value);if(!stock){toast('Selecione um material.','error');return}if(g<=0){toast('Informe as gramas.','error');return}if(g>num(stock.qtde)){toast('A quantidade informada excede o estoque disponível.','error');return}if(materialList.some(m=>m.estoqueId===stock.id)){toast('Este material já foi adicionado.','error');return}materialList.push({estoqueId:stock.id,descricao:stock.descricao,gramas:g,corId:stock.corId});sync();select.value='';color.value='';grams.value='';picker.classList.add('hidden')};sync()},0)}
function applyFinishedProduction(o){o.materiais.forEach(m=>{const stock=db.estoque.find(x=>x.id===m.estoqueId);if(stock)stock.qtde=Math.max(0,num(stock.qtde)-num(m.gramas))});const p=db.produtos.find(x=>x.id===o.produtoId);if(p)p.qtde=num(p.qtde)+num(o.qtde);o.finishedApplied=true}
window.deleteOP=id=>{if(!confirm('Excluir a ordem de produção?'))return;db.producoes=db.producoes.filter(x=>x.id!==id);saveDB();renderProducao(document.getElementById('module-root'));toast('Ordem excluída.','error')};
window.generateSale=id=>{const o=db.producoes.find(x=>x.id===id);setModule('vendas');setTimeout(()=>openSaleModal(null,o),0)};

function renderVendas(root){root.innerHTML=`<div class="section-head"><div><h2>Vendas</h2><p>Registre pedidos e gere automaticamente o lançamento financeiro.</p></div><button class="btn btn-primary" id="add-sale">+ Nova venda</button></div><div class="card panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Data</th><th>Cliente</th><th>Produto</th><th>Qtde</th><th>Cor</th><th>Valor unit.</th><th>Desconto</th><th>Valor final</th><th>Ações</th></tr></thead><tbody>${db.vendas.length?db.vendas.map(s=>`<tr><td>${dateBR(s.data)}</td><td>${esc(db.cadastros.clientes.find(c=>c.id===s.clienteId)?.nome||'-')}</td><td>${esc(db.produtos.find(p=>p.id===s.produtoId)?.descricao||'-')}</td><td>${num(s.qtde)}</td><td>${esc(db.cadastros.cores.find(c=>c.id===s.corId)?.descricao||'-')}</td><td>${money(s.valorUnit)}</td><td>${num(s.desconto).toFixed(2)}%</td><td><strong>${money(s.valorFinal)}</strong></td><td><div class="actions"><button class="small-btn" onclick="openSaleModal('${s.id}')">Editar</button><button class="small-btn" onclick="deleteSale('${s.id}')">Excluir</button></div></td></tr>`).join(''):`<tr><td colspan="9"><div class="empty-state">Nenhuma venda registrada.</div></td></tr>`}</tbody></table></div></div>`;document.getElementById('add-sale').onclick=()=>openSaleModal()}
function saleForm(r={},op){const productionProductIds=new Set(db.producoes.map(x=>x.produtoId));const productOptions=db.produtos.filter(x=>r.produtoId===x.id||op?.produtoId===x.id||productionProductIds.has(x.id));return `<div class="form-grid"><label class="col-6">Cliente *<select id="v_client" required><option value="">Selecione</option>${db.cadastros.clientes.map(x=>`<option value="${x.id}" ${r.clienteId===x.id?'selected':''}>${esc(x.nome)}</option>`).join('')}</select></label><label class="col-6">Produto *<select id="v_prod" required><option value="">Selecione</option>${productOptions.map(x=>`<option value="${x.id}" ${(r.produtoId||op?.produtoId)===x.id?'selected':''}>${esc(x.descricao)}</option>`).join('')}</select></label><label class="col-3">Qtde *<input id="v_q" type="number" min="1" value="${r.qtde||op?.qtde||1}" required></label><label class="col-3">Cor *<select id="v_cor" required><option value="">Selecione</option>${db.cadastros.cores.map(x=>`<option value="${x.id}" ${(r.corId||op?.corId)===x.id?'selected':''}>${esc(x.descricao)}</option>`).join('')}</select></label><label class="col-3">Valor unitário (R$) *<input id="v_unit" inputmode="decimal" value="${r.valorUnit??(op?db.produtos.find(p=>p.id===op.produtoId)?.preco:'')}" required></label><label class="col-3">Desconto (%)<input id="v_disc" inputmode="decimal" value="${r.desconto??0}"></label><label class="col-12">Observações<textarea id="v_obs">${esc(r.observacoes||'')}</textarea></label><label class="col-12">Valor final calculado<input id="v_final" readonly value="${money(r.valorFinal||0)}"></label>${op?`<div class="col-12 inline-note">Ordem de produção vinculada: ${esc(op.id)}</div>`:''}</div>`}
function openSaleModal(id,op){const r=id?db.vendas.find(x=>x.id===id)||{}:{};openModal('Vendas',id?'Editar venda':'Nova venda',saleForm(r,op),()=>{const client=document.getElementById('v_client').value,prod=document.getElementById('v_prod').value,cor=document.getElementById('v_cor').value,q=num(document.getElementById('v_q').value),unit=num(document.getElementById('v_unit').value),disc=num(document.getElementById('v_disc').value);if(!client||!prod||!cor||q<=0||unit<=0){toast('Preencha os campos obrigatórios.','error');return}const final=q*unit*(1-disc/100);const obj={id:r.id||uid('VEN'),data:r.data||nowISO(),clienteId:client,produtoId:prod,qtde:q,corId:cor,valorUnit:unit,desconto:disc,valorFinal:final,observacoes:document.getElementById('v_obs').value.trim(),opId:op?.codigo||r.opId||null};if(id)Object.assign(r,obj);else{db.vendas.push(obj);db.financeiro.push({id:uid('FIN'),data:obj.data,clienteId:obj.clienteId,produtoId:obj.produtoId,opId:obj.opId,qtde:obj.qtde,status:'Aberto',valor:obj.valorFinal,vendaId:obj.id})}saveDB();closeModal();renderVendas(document.getElementById('module-root'));toast('Venda registrada e financeiro atualizado.')});setTimeout(()=>{const u=()=>{const q=num(document.getElementById('v_q')?.value),unit=num(document.getElementById('v_unit')?.value),disc=num(document.getElementById('v_disc')?.value);if(document.getElementById('v_final'))document.getElementById('v_final').value=money(q*unit*(1-disc/100))};['v_q','v_unit','v_disc'].forEach(x=>document.getElementById(x)?.addEventListener('input',u));u()},0)}
window.openSaleModal=openSaleModal;window.deleteSale=id=>{if(!confirm('Excluir venda e lançamento financeiro vinculado?'))return;db.vendas=db.vendas.filter(x=>x.id!==id);db.financeiro=db.financeiro.filter(x=>x.vendaId!==id);saveDB();renderVendas(document.getElementById('module-root'));toast('Venda excluída.','error')};

function productionRefLabel(ref){const o=db.producoes.find(x=>x.id===ref||x.codigo===ref);return o?.codigo||ref||'-'}
function renderFinanceiro(root){root.innerHTML=`<div class="section-head"><div><h2>Financeiro</h2><p>Acompanhe os lançamentos gerados pelas vendas.</p></div></div><div class="filters"><label>Data<input type="date" id="f_date"></label><label>Cliente<select id="f_client"><option value="">Todos</option>${db.cadastros.clientes.map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('')}</select></label><label>Produto<select id="f_prod"><option value="">Todos</option>${db.produtos.map(x=>`<option value="${x.id}">${esc(x.descricao)}</option>`).join('')}</select></label><label>Status<select id="f_status"><option value="">Todos</option><option>Aberto</option><option>Faturado</option></select></label></div><div class="card panel"><div id="fin-table"></div></div>`;['f_date','f_client','f_prod','f_status'].forEach(x=>document.getElementById(x).addEventListener('input',renderFinanceTable));renderFinanceTable()}
function renderFinanceTable(){const dt=document.getElementById('f_date').value,cl=document.getElementById('f_client').value,pr=document.getElementById('f_prod').value,st=document.getElementById('f_status').value;const rows=db.financeiro.filter(x=>(!dt||x.data.slice(0,10)===dt)&&(!cl||x.clienteId===cl)&&(!pr||x.produtoId===pr)&&(!st||x.status===st));const total=rows.reduce((sum,x)=>sum+num(x.valor),0),open=rows.filter(x=>x.status==='Aberto').reduce((sum,x)=>sum+num(x.valor),0),billed=rows.filter(x=>x.status==='Faturado').reduce((sum,x)=>sum+num(x.valor),0);const host=document.getElementById('fin-table');host.innerHTML=`<div class="cards finance-totals"><div class="card metric"><div class="label">Valor total</div><div class="value">${money(total)}</div><div class="sub">Registros filtrados</div></div><div class="card metric"><div class="label">Em aberto</div><div class="value">${money(open)}</div><div class="sub">Status Aberto</div></div><div class="card metric"><div class="label">Faturado</div><div class="value">${money(billed)}</div><div class="sub">Status Faturado</div></div></div>`+(rows.length?`<table class="data-table"><thead><tr><th>Data</th><th>Cliente</th><th>Produto</th><th>Ordem Produção</th><th>Qtde</th><th>Status</th><th>Valor</th><th>Ações</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${dateBR(x.data)}</td><td>${esc(db.cadastros.clientes.find(c=>c.id===x.clienteId)?.nome||'-')}</td><td>${esc(db.produtos.find(p=>p.id===x.produtoId)?.descricao||'-')}</td><td>${esc(productionRefLabel(x.opId))}</td><td>${num(x.qtde)}</td><td><span class="status-pill ${x.status==='Faturado'?'status-billed':'status-open'}">${x.status}</span></td><td><strong>${money(x.valor)}</strong></td><td><div class="actions"><button class="small-btn" onclick="exportFinancePdf('${x.id}')">Exportar PDF</button><button class="small-btn" onclick="changeFinStatus('${x.id}')">Alterar Status</button><button class="small-btn" onclick="deleteFinance('${x.id}')">Excluir</button></div></td></tr>`).join('')}</tbody></table>`:`<div class="empty-state"><strong>Nenhum lançamento</strong>Não há registros com os filtros atuais.</div>`)}
function exportFinancePdf(id){const f=db.financeiro.find(x=>x.id===id);const {jsPDF}=window.jspdf||{};if(!jsPDF){toast('Biblioteca de PDF indisponível.','error');return}const doc=new jsPDF();doc.setFontSize(18);doc.text('Navora 3D — Lançamento Financeiro',20,20);doc.setFontSize(11);const cliente=db.cadastros.clientes.find(c=>c.id===f.clienteId)?.nome||'-';const prod=db.produtos.find(p=>p.id===f.produtoId)?.descricao||'-';[['Data',dateBR(f.data)],['Cliente',cliente],['Produto',prod],['Ordem de Produção',productionRefLabel(f.opId)],['Quantidade',String(f.qtde)],['Status',f.status],['Valor',money(f.valor)]].forEach((r,i)=>{doc.text(`${r[0]}: ${r[1]}`,20,42+i*10)});doc.save(`navora3d-financeiro-${f.id}.pdf`)}
window.exportFinancePdf=exportFinancePdf;window.changeFinStatus=id=>{const f=db.financeiro.find(x=>x.id===id);openModal('Alterar status','Lançamento financeiro',`<label>Status<select id="fin_status"><option ${f.status==='Aberto'?'selected':''}>Aberto</option><option ${f.status==='Faturado'?'selected':''}>Faturado</option></select></label>`,()=>{f.status=document.getElementById('fin_status').value;saveDB();closeModal();renderFinanceiro(document.getElementById('module-root'));toast('Status atualizado.')})};window.deleteFinance=id=>{if(!confirm('Excluir este lançamento financeiro?'))return;db.financeiro=db.financeiro.filter(x=>x.id!==id);saveDB();renderFinanceiro(document.getElementById('module-root'));toast('Lançamento excluído.','error')};

function renderConfiguracoes(root){root.innerHTML=`<div class="section-head"><div><h2>Configurações</h2><p>Backup, restauração e administração local da base.</p></div></div><div class="grid-2"><div class="card panel"><h3>Backup</h3><p class="muted">Exporte todos os dados da Navora 3D em JSON.</p><button class="btn btn-primary" id="export-json">Exportar backup JSON</button></div><div class="card panel"><h3>Restauração</h3><p class="muted">Importe um backup JSON completo para recuperar sua base.</p><input id="import-json" type="file" accept="application/json,.json"><div style="height:8px"></div><button class="btn btn-secondary" id="import-btn">Importar e restaurar</button></div><div class="card panel"><h3>Base local</h3><p class="muted">Todos os dados estão salvos localmente no navegador deste dispositivo.</p><div class="inline-note">Última atualização: ${dateBR(db.meta.updatedAt)} ${new Date(db.meta.updatedAt).toLocaleTimeString('pt-BR')}</div></div><div class="card panel"><h3>Dados demo</h3><p class="muted">Pode carregar uma base inicial para testar o fluxo completo.</p><button class="btn btn-danger" id="clear-db">Limpar toda a base</button></div></div>`;document.getElementById('export-json').onclick=exportBackup;document.getElementById('import-btn').onclick=importBackup;document.getElementById('clear-db').onclick=()=>{if(!confirm('Esta ação apagará todos os dados locais.'))return;db=blankDB();saveDB();toast('Base limpa.','error');renderConfiguracoes(root)}}
function exportBackup(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`navora3d-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Backup exportado.')}
function importBackup(){const file=document.getElementById('import-json').files[0];if(!file){toast('Selecione um arquivo JSON.','error');return}const fr=new FileReader();fr.onload=()=>{try{const data=JSON.parse(fr.result);if(!data.cadastros||!data.produtos)throw new Error('Formato inválido');db=data;saveDB();toast('Backup restaurado com sucesso.');renderConfiguracoes(document.getElementById('module-root'))}catch(e){toast('Arquivo inválido ou corrompido.','error')}};fr.readAsText(file)}

function openModal(title,subtitle,body,onSave){const root=document.getElementById('modal-root');root.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><h3>${esc(title)}</h3><div class="muted" style="font-size:12px;margin-top:3px">${esc(subtitle||'')}</div></div><button class="icon-btn" id="modal-close">×</button></div><div class="modal-body">${body||''}</div>${onSave?`<div class="modal-foot"><button class="btn btn-secondary" id="modal-cancel">Cancelar</button><button class="btn btn-primary" id="modal-save">Salvar</button></div>`:''}</div></div>`;document.getElementById('modal-close').onclick=closeModal;document.getElementById('modal-cancel')?.addEventListener('click',closeModal);document.getElementById('modal-save')?.addEventListener('click',onSave);document.querySelector('.modal-backdrop').addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop'))closeModal()});document.querySelectorAll('.op-mat').forEach(s=>s.addEventListener('change',()=>{document.querySelector(`.op-g[data-id="${s.dataset.id}"]`).disabled=!s.value}))}
function closeModal(){document.getElementById('modal-root').innerHTML=''}

document.addEventListener('DOMContentLoaded',()=>{
 document.getElementById('today-label').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short',year:'numeric'});
 document.getElementById('login-form').addEventListener('submit',e=>{e.preventDefault();if(document.getElementById('login-user').value===LOGIN.user&&document.getElementById('login-pass').value===LOGIN.pass){sessionStorage.setItem('navora3d_auth','1');document.getElementById('login-screen').classList.add('hidden');document.getElementById('app-shell').classList.remove('hidden');setModule('dashboard')}else toast('Usuário ou senha inválidos.','error')});
 document.querySelectorAll('.nav-item[data-module]').forEach(b=>b.addEventListener('click',()=>{setModule(b.dataset.module);document.querySelector('.sidebar').classList.remove('open')}));document.getElementById('logout-btn').addEventListener('click',()=>{sessionStorage.removeItem('navora3d_auth');document.getElementById('app-shell').classList.add('hidden');document.getElementById('login-screen').classList.remove('hidden')});document.getElementById('mobile-menu').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));
 if(sessionStorage.getItem('navora3d_auth')==='1'){document.getElementById('login-screen').classList.add('hidden');document.getElementById('app-shell').classList.remove('hidden');setModule('dashboard')}
});
